import type { Config, Preview } from './types';

export const TOP_LEVEL_ORDER = Object.freeze([
  'use_minimessage',
  'force_tags',
  'check_updates',
  'legacy_hex',
  'papi_chat',
  'format_chat',
  'load_tag_on_join',
  'gui',
  'categories',
  'deluxetags',
]);

export const STATIC_ITEM_KEYS = Object.freeze([
  'divider_item',
  'has_tag_item',
  'no_tag_item',
  'exit_item',
  'category_back_item',
  'next_page',
  'previous_page',
]);

export const DEFAULT_ICON_TEMPLATE =
  'https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.21.4/assets/minecraft/textures/{folder}/{id}.png';

export const MINI_COLORS: Readonly<Record<string, string>> = Object.freeze({
  black: '&0',
  dark_blue: '&1',
  dark_green: '&2',
  dark_aqua: '&3',
  dark_red: '&4',
  dark_purple: '&5',
  gold: '&6',
  gray: '&7',
  grey: '&7',
  dark_gray: '&8',
  dark_grey: '&8',
  blue: '&9',
  green: '&a',
  aqua: '&b',
  red: '&c',
  light_purple: '&d',
  yellow: '&e',
  white: '&f',
});

export const LEGACY_COLORS: Readonly<Record<string, string>> = Object.freeze({
  '0': '#000000',
  '1': '#0000aa',
  '2': '#00aa00',
  '3': '#00aaaa',
  '4': '#aa0000',
  '5': '#aa00aa',
  '6': '#ffaa00',
  '7': '#aaaaaa',
  '8': '#555555',
  '9': '#5555ff',
  a: '#55ff55',
  b: '#55ffff',
  c: '#ff5555',
  d: '#ff55ff',
  e: '#ffff55',
  f: '#ffffff',
});

export const LEGACY_FORMATS: Readonly<Record<string, string>> = Object.freeze({
  l: 'bold',
  o: 'italic',
  n: 'underline',
  m: 'strikethrough',
  k: 'obfuscated',
});

export const KNOWN_MINI_TAGS: ReadonlySet<string> = new Set([
  ...Object.keys(MINI_COLORS),
  'color',
  'colour',
  'c',
  'shadow',
  'bold',
  'b',
  'italic',
  'em',
  'i',
  'underlined',
  'u',
  'strikethrough',
  'st',
  'obfuscated',
  'obf',
  'reset',
  'newline',
  'br',
  'gradient',
  'rainbow',
  'transition',
  'font',
  'click',
  'hover',
  'keybind',
  'key',
  'lang',
  'tr',
  'translate',
  'lang_or',
  'tr_or',
  'translate_or',
  'insert',
  'selector',
  'sel',
  'score',
  'nbt',
  'data',
  'pride',
  'sprite',
  'head',
]);

export const KNOWN_PLACEHOLDERS: ReadonlySet<string> = new Set([
  'player',
  'displayname',
  'deluxetags_tag',
  'deluxetags_identifier',
  'deluxetags_description',
  'deluxetags_amount',
  'deluxetags_category_amount',
  'deluxetags_available',
  'previous_page',
  'current_page',
  'next_page',
]);

export const COMMON_MATERIALS: ReadonlySet<string> = new Set([
  'AIR',
  'ARROW',
  'BARRIER',
  'BLACK_STAINED_GLASS_PANE',
  'BOOK',
  'CHEST',
  'CLOCK',
  'COMPASS',
  'DIAMOND',
  'DIAMOND_BLOCK',
  'DIAMOND_SWORD',
  'EMERALD',
  'EMERALD_BLOCK',
  'ENDER_PEARL',
  'FEATHER',
  'GOLD_INGOT',
  'GOLD_BLOCK',
  'GOLDEN_APPLE',
  'GRASS_BLOCK',
  'GRAY_STAINED_GLASS_PANE',
  'GREEN_STAINED_GLASS_PANE',
  'IRON_DOOR',
  'IRON_INGOT',
  'LIME_STAINED_GLASS_PANE',
  'NAME_TAG',
  'NETHER_STAR',
  'PAPER',
  'PLAYER_HEAD',
  'RED_STAINED_GLASS_PANE',
  'REDSTONE',
  'REDSTONE_TORCH',
  'STONE',
  'WHITE_STAINED_GLASS_PANE',
  'WRITABLE_BOOK',
  'WRITTEN_BOOK',
  'YELLOW_STAINED_GLASS_PANE',
]);

export const MATERIAL_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  CREEPER_WALL_HEAD: 'CREEPER_HEAD',
  PIGLIN_WALL_HEAD: 'PIGLIN_HEAD',
  PLAYER_SKULL: 'PLAYER_HEAD',
  PLAYER_WALL_HEAD: 'PLAYER_HEAD',
  SKULL: 'PLAYER_HEAD',
  SKULL_ITEM: 'PLAYER_HEAD',
  SKELETON_WALL_SKULL: 'SKELETON_SKULL',
  WITHER_SKELETON_WALL_SKULL: 'WITHER_SKELETON_SKULL',
  ZOMBIE_WALL_HEAD: 'ZOMBIE_HEAD',
});

export const MINI_FORMAT_CODES: Readonly<Record<string, string>> = Object.freeze({
  bold: '&l',
  b: '&l',
  italic: '&o',
  em: '&o',
  i: '&o',
  underlined: '&n',
  u: '&n',
  strikethrough: '&m',
  st: '&m',
  obfuscated: '&k',
  obf: '&k',
});

export const MINI_FORMAT_CANONICAL: Readonly<Record<string, string>> = Object.freeze({
  bold: 'bold',
  b: 'bold',
  italic: 'italic',
  em: 'italic',
  i: 'italic',
  underlined: 'underlined',
  u: 'underlined',
  strikethrough: 'strikethrough',
  st: 'strikethrough',
  obfuscated: 'obfuscated',
  obf: 'obfuscated',
});

export const DEFAULT_CONFIG = Object.freeze({
  use_minimessage: false,
  force_tags: false,
  check_updates: true,
  legacy_hex: false,
  papi_chat: true,
  format_chat: {
    enabled: false,
    format: '{deluxetags_tag} <%1$s> %2$s',
  },
  load_tag_on_join: true,
  gui: {
    tag_availability_placeholder: {
      has_permission: '&aTag unlocked! Click to select',
      no_permission: '&cTag locked ',
    },
    name: '&6Available tags&f: &6%deluxetags_amount%',
    size: 54,
    tag_slots: ['0-35'],
    tag_visible_item: {
      material: 'BARRIER',
      data: 0,
    },
    divider_item: {
      material: 'BLACK_STAINED_GLASS_PANE',
      data: 0,
      displayname: '',
      lore: [],
      slots: ['36-44'],
    },
    has_tag_item: {
      material: 'PLAYER_HEAD',
      data: 0,
      displayname: '&eCurrent tag&f: &6%deluxetags_identifier%',
      lore: ['%deluxetags_tag%', 'Click to remove your current tag'],
      slots: ['49'],
    },
    no_tag_item: {
      material: 'PLAYER_HEAD',
      data: 0,
      displayname: "&cYou don't have a tag set!",
      lore: ['&7Click a tag above to select one!'],
      slots: ['49'],
    },
    exit_item: {
      material: 'IRON_DOOR',
      data: 0,
      displayname: '&cClick to exit',
      lore: ['&7Exit the tags menu'],
      slots: ['48', '50'],
    },
    category_back_item: {
      material: 'ARROW',
      data: 0,
      displayname: '&6Back to categories',
      lore: ['&7Return to category selection'],
      slots: ['47'],
    },
    next_page: {
      material: 'PAPER',
      data: 0,
      displayname: '&6Next page: %next_page%',
      lore: ['&7Move to the next page'],
      slots: ['53'],
    },
    previous_page: {
      material: 'PAPER',
      data: 0,
      displayname: '&6Previous page: %previous_page%',
      lore: ['&7Move to the previous page'],
      slots: ['45'],
    },
  },
  categories: {
    all: {
      order: 0,
      item: 'BOOK',
      name: '&6All Tags',
      lore: ['&7Click to view all available tags'],
      gui_name: '&6All Tags',
    },
    general: {
      order: 1,
      item: 'NAME_TAG',
      name: '&6General',
      lore: ['&7Click to view general tags'],
      gui_name: '&6General tags',
    },
  },
  deluxetags: {
    example: {
      order: 1,
      category: 'general',
      tag: '&8[&bDeluxeTags&8]',
      displayname: '&6Tag&f: &6%deluxetags_identifier%',
      description: ['&cAwarded for using DeluxeTags!', '%deluxetags_available%'],
      item: 'NAME_TAG',
      data: 0,
      permission: 'deluxetags.tag.example',
    },
  },
}) as unknown as Config;

export const DEFAULT_PREVIEW = Object.freeze({
  page: 1,
  screen: 'auto',
  category: 'all',
  playerName: 'Steve',
  displayName: 'Steve',
  activeTagId: 'example',
  permissionMode: 'all',
  unlockedTags: {},
  showLockedTags: true,
  iconTemplate: DEFAULT_ICON_TEMPLATE,
  parsePlaceholders: true,
}) as unknown as Preview;
